/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "common.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ecg_streaming_ECGSample, ecg_streaming_ECGSample, AUTO)


PB_BIND(ecg_streaming_AccelerometerSample, ecg_streaming_AccelerometerSample, AUTO)





