/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_ECG_STREAMING_COMMON_PB_H_INCLUDED
#define PB_ECG_STREAMING_COMMON_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Device connection and streaming status */
typedef enum _ecg_streaming_DeviceStatus {
    ecg_streaming_DeviceStatus_DEVICE_STATUS_UNKNOWN = 0,
    ecg_streaming_DeviceStatus_DEVICE_STATUS_DISCONNECTED = 1,
    ecg_streaming_DeviceStatus_DEVICE_STATUS_CONNECTING = 2,
    ecg_streaming_DeviceStatus_DEVICE_STATUS_CONNECTED = 3,
    ecg_streaming_DeviceStatus_DEVICE_STATUS_STREAMING = 4,
    ecg_streaming_DeviceStatus_DEVICE_STATUS_ERROR = 5
} ecg_streaming_DeviceStatus;

/* Struct definitions */
/* Individual ECG sample with precise timestamp */
typedef struct _ecg_streaming_ECGSample {
    int32_t value; /* Raw ECG value (μV or device units) */
    uint64_t polar_clock_us; /* Polar device clock (microseconds since Polar boot) */
} ecg_streaming_ECGSample;

/* Individual accelerometer sample with precise timestamp */
typedef struct _ecg_streaming_AccelerometerSample {
    float x; /* X-axis acceleration (g) */
    float y; /* Y-axis acceleration (g) */
    float z; /* Z-axis acceleration (g) */
    uint64_t polar_clock_us; /* Polar device clock (microseconds since Polar boot) */
} ecg_streaming_AccelerometerSample;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _ecg_streaming_DeviceStatus_MIN ecg_streaming_DeviceStatus_DEVICE_STATUS_UNKNOWN
#define _ecg_streaming_DeviceStatus_MAX ecg_streaming_DeviceStatus_DEVICE_STATUS_ERROR
#define _ecg_streaming_DeviceStatus_ARRAYSIZE ((ecg_streaming_DeviceStatus)(ecg_streaming_DeviceStatus_DEVICE_STATUS_ERROR+1))




/* Initializer values for message structs */
#define ecg_streaming_ECGSample_init_default     {0, 0}
#define ecg_streaming_AccelerometerSample_init_default {0, 0, 0, 0}
#define ecg_streaming_ECGSample_init_zero        {0, 0}
#define ecg_streaming_AccelerometerSample_init_zero {0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define ecg_streaming_ECGSample_value_tag        1
#define ecg_streaming_ECGSample_polar_clock_us_tag 2
#define ecg_streaming_AccelerometerSample_x_tag  1
#define ecg_streaming_AccelerometerSample_y_tag  2
#define ecg_streaming_AccelerometerSample_z_tag  3
#define ecg_streaming_AccelerometerSample_polar_clock_us_tag 4

/* Struct field encoding specification for nanopb */
#define ecg_streaming_ECGSample_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    value,             1) \
X(a, STATIC,   SINGULAR, UINT64,   polar_clock_us,    2)
#define ecg_streaming_ECGSample_CALLBACK NULL
#define ecg_streaming_ECGSample_DEFAULT NULL

#define ecg_streaming_AccelerometerSample_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    x,                 1) \
X(a, STATIC,   SINGULAR, FLOAT,    y,                 2) \
X(a, STATIC,   SINGULAR, FLOAT,    z,                 3) \
X(a, STATIC,   SINGULAR, UINT64,   polar_clock_us,    4)
#define ecg_streaming_AccelerometerSample_CALLBACK NULL
#define ecg_streaming_AccelerometerSample_DEFAULT NULL

extern const pb_msgdesc_t ecg_streaming_ECGSample_msg;
extern const pb_msgdesc_t ecg_streaming_AccelerometerSample_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ecg_streaming_ECGSample_fields &ecg_streaming_ECGSample_msg
#define ecg_streaming_AccelerometerSample_fields &ecg_streaming_AccelerometerSample_msg

/* Maximum encoded size of messages (where known) */
#define ECG_STREAMING_COMMON_PB_H_MAX_SIZE       ecg_streaming_AccelerometerSample_size
#define ecg_streaming_AccelerometerSample_size   26
#define ecg_streaming_ECGSample_size             22

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
