/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "ecg_streaming.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ecg_streaming_UsbFrame, ecg_streaming_UsbFrame, AUTO)


PB_BIND(ecg_streaming_CollectorMessage, ecg_streaming_CollectorMessage, 2)


PB_BIND(ecg_streaming_AggregatorMessage, ecg_streaming_AggregatorMessage, 2)


PB_BIND(ecg_streaming_CollectorRegistration, ecg_streaming_CollectorRegistration, 2)


PB_BIND(ecg_streaming_CollectorRegistration_MetadataEntry, ecg_streaming_CollectorRegistration_MetadataEntry, AUTO)


PB_BIND(ecg_streaming_RegistrationAck, ecg_streaming_RegistrationAck, AUTO)


PB_BIND(ecg_streaming_ECGSampleBatch, ecg_streaming_ECGSampleBatch, 2)


PB_BIND(ecg_streaming_ECGSample, ecg_streaming_ECGSample, AUTO)


PB_BIND(ecg_streaming_AccelerometerSampleBatch, ecg_streaming_AccelerometerSampleBatch, 2)


PB_BIND(ecg_streaming_AccelerometerSample, ecg_streaming_AccelerometerSample, AUTO)


PB_BIND(ecg_streaming_DeviceStatusUpdate, ecg_streaming_DeviceStatusUpdate, 2)


PB_BIND(ecg_streaming_DeviceStatusUpdate_DeviceInfoEntry, ecg_streaming_DeviceStatusUpdate_DeviceInfoEntry, AUTO)


PB_BIND(ecg_streaming_CollectorHeartbeat, ecg_streaming_CollectorHeartbeat, AUTO)


PB_BIND(ecg_streaming_SyncStatusUpdate, ecg_streaming_SyncStatusUpdate, AUTO)


PB_BIND(ecg_streaming_ControlCommand, ecg_streaming_ControlCommand, 2)


PB_BIND(ecg_streaming_ControlCommand_ParametersEntry, ecg_streaming_ControlCommand_ParametersEntry, AUTO)


PB_BIND(ecg_streaming_UsbDeviceInfo, ecg_streaming_UsbDeviceInfo, AUTO)


PB_BIND(ecg_streaming_UsbConfig, ecg_streaming_UsbConfig, AUTO)


PB_BIND(ecg_streaming_UsbConfigAck, ecg_streaming_UsbConfigAck, 2)


PB_BIND(ecg_streaming_BleNotificationDebug, ecg_streaming_BleNotificationDebug, AUTO)









#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

