/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "esp_collector.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ecg_streaming_EspMessage, ecg_streaming_EspMessage, 2)


PB_BIND(ecg_streaming_SensorFrame, ecg_streaming_SensorFrame, AUTO)


PB_BIND(ecg_streaming_UsbDeviceInfo, ecg_streaming_UsbDeviceInfo, AUTO)


PB_BIND(ecg_streaming_UsbConfigAck, ecg_streaming_UsbConfigAck, 2)


PB_BIND(ecg_streaming_BleNotificationDebug, ecg_streaming_BleNotificationDebug, AUTO)


PB_BIND(ecg_streaming_BleScanSighting, ecg_streaming_BleScanSighting, AUTO)


PB_BIND(ecg_streaming_BleScanResult, ecg_streaming_BleScanResult, 2)


PB_BIND(ecg_streaming_EspDiscoveryMessage, ecg_streaming_EspDiscoveryMessage, 2)


PB_BIND(ecg_streaming_CollectorToEspMessage, ecg_streaming_CollectorToEspMessage, AUTO)


PB_BIND(ecg_streaming_UsbConfig, ecg_streaming_UsbConfig, AUTO)


PB_BIND(ecg_streaming_StartBleScan, ecg_streaming_StartBleScan, AUTO)





