/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_ECG_STREAMING_ESP_COLLECTOR_PB_H_INCLUDED
#define PB_ECG_STREAMING_ESP_COLLECTOR_PB_H_INCLUDED
#include <pb.h>
#include "common.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Sensor type enumeration */
typedef enum _ecg_streaming_SensorType {
    ecg_streaming_SensorType_SENSOR_TYPE_ECG = 0,
    ecg_streaming_SensorType_SENSOR_TYPE_ACCELEROMETER = 1
} ecg_streaming_SensorType;

/* Struct definitions */
/* Unified sensor frame from Polar device (ECG or Accelerometer)
 ESP32 receives PMD frame from Polar H10, timestamps it with local time, and forwards */
typedef struct _ecg_streaming_SensorFrame {
    char device_id[65]; /* Polar device ID (e.g., "Polar H10 ABC123") */
    ecg_streaming_SensorType sensor_type; /* Type of sensor data (ECG or ACC) */
    uint64_t polar_clock_us; /* Polar device clock - microseconds since Polar device boot (last sample timestamp) */
    uint64_t receiver_clock_us; /* Receiver device clock - microseconds since receiver boot (ESP32 or collector) */
    /* NOTE: This is NOT always epoch time! */
    int32_t sample_rate; /* Sample rate in Hz */
    pb_callback_t raw_data; /* Raw PMD frame data (unparsed, for collector to process) */
} ecg_streaming_SensorFrame;

/* Configuration acknowledgment from ESP32
 Response to UsbConfig command */
typedef struct _ecg_streaming_UsbConfigAck {
    char esp_id[65]; /* ESP32 identifier */
    bool accepted; /* True if configuration was accepted */
    char message[129]; /* Human-readable status/error message */
    char target_device_id[65]; /* Configured target device ID (if accepted) */
} ecg_streaming_UsbConfigAck;

/* Debug telemetry for BLE PMD notifications
 Used for debugging ESP32-Polar communication issues */
typedef struct _ecg_streaming_BleNotificationDebug {
    char device_id[65]; /* Polar device ID */
    uint32_t frame_type; /* PMD frame type */
    uint32_t pmd_type; /* PMD measurement type */
    uint32_t notif_len; /* Notification length in bytes */
    uint32_t sample_count; /* Number of samples in notification */
    uint64_t polar_clock_us; /* Polar device clock (microseconds since Polar boot) */
    uint32_t interval_us; /* Time since last notification (microseconds) */
    uint64_t notification_index; /* Sequential notification counter */
    uint32_t conn_interval_ms; /* BLE connection interval (ms) */
    uint32_t mtu; /* Negotiated MTU */
} ecg_streaming_BleNotificationDebug;

/* Configuration for a single Polar target */
typedef struct _ecg_streaming_UsbTargetConfig {
    char target_device_id[65]; /* Polar device ID to connect to */
    int32_t ecg_sample_rate; /* Requested ECG sample rate (Hz) */
    int32_t acc_sample_rate; /* Requested accelerometer sample rate (Hz) */
} ecg_streaming_UsbTargetConfig;

/* Per-target status info reported by ESP32 */
typedef struct _ecg_streaming_UsbTargetInfo {
    char target_device_id[65]; /* Polar device ID configured on this link */
    bool polar_connected; /* True if link is connected */
    ecg_streaming_DeviceStatus polar_status; /* Connection status for this target */
    int32_t ecg_sample_rate; /* Effective ECG sample rate (Hz) */
    int32_t acc_sample_rate; /* Effective ACC sample rate (Hz) */
} ecg_streaming_UsbTargetInfo;

/* USB device identity and status information
 Sent by ESP32 on connection or when status changes */
typedef struct _ecg_streaming_UsbDeviceInfo {
    char esp_id[65]; /* Unique ESP32 identifier (e.g., MAC address) */
    char firmware_version[33]; /* ESP32 firmware version */
    bool config_required; /* True if ESP needs configuration before starting */
    bool polar_connected; /* True if currently connected to Polar device */
    ecg_streaming_DeviceStatus polar_status; /* Status of Polar device connection */
    pb_size_t targets_count;
    ecg_streaming_UsbTargetInfo targets[2]; /* Per-target status (one entry per configured target) */
} ecg_streaming_UsbDeviceInfo;

typedef struct _ecg_streaming_EspMessage {
    pb_size_t which_message;
    union {
        ecg_streaming_SensorFrame sensor_frame;
        ecg_streaming_UsbDeviceInfo device_info;
        ecg_streaming_UsbConfigAck config_ack;
        ecg_streaming_BleNotificationDebug ble_debug;
    } message;
} ecg_streaming_EspMessage;

/* Configuration command for ESP32
 Tells ESP32 which Polar device to connect to and streaming parameters */
typedef struct _ecg_streaming_UsbConfig {
    char esp_id[65]; /* Target ESP32 identifier */
    pb_size_t targets_count;
    ecg_streaming_UsbTargetConfig targets[2]; /* One or more target devices to connect to */
    bool persist; /* If true, save config to ESP32 flash */
} ecg_streaming_UsbConfig;

typedef struct _ecg_streaming_CollectorToEspMessage {
    pb_size_t which_message;
    union {
        ecg_streaming_UsbConfig config;
    } message;
} ecg_streaming_CollectorToEspMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _ecg_streaming_SensorType_MIN ecg_streaming_SensorType_SENSOR_TYPE_ECG
#define _ecg_streaming_SensorType_MAX ecg_streaming_SensorType_SENSOR_TYPE_ACCELEROMETER
#define _ecg_streaming_SensorType_ARRAYSIZE ((ecg_streaming_SensorType)(ecg_streaming_SensorType_SENSOR_TYPE_ACCELEROMETER+1))


#define ecg_streaming_SensorFrame_sensor_type_ENUMTYPE ecg_streaming_SensorType

#define ecg_streaming_UsbDeviceInfo_polar_status_ENUMTYPE ecg_streaming_DeviceStatus





#define ecg_streaming_UsbTargetInfo_polar_status_ENUMTYPE ecg_streaming_DeviceStatus



/* Initializer values for message structs */
#define ecg_streaming_EspMessage_init_default    {0, {ecg_streaming_SensorFrame_init_default}}
#define ecg_streaming_SensorFrame_init_default   {"", _ecg_streaming_SensorType_MIN, 0, 0, 0, {{NULL}, NULL}}
#define ecg_streaming_UsbDeviceInfo_init_default {"", "", 0, 0, _ecg_streaming_DeviceStatus_MIN, 0, {ecg_streaming_UsbTargetInfo_init_default, ecg_streaming_UsbTargetInfo_init_default}}
#define ecg_streaming_UsbConfigAck_init_default  {"", 0, "", ""}
#define ecg_streaming_BleNotificationDebug_init_default {"", 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define ecg_streaming_CollectorToEspMessage_init_default {0, {ecg_streaming_UsbConfig_init_default}}
#define ecg_streaming_UsbTargetConfig_init_default {"", 0, 0}
#define ecg_streaming_UsbTargetInfo_init_default {"", 0, _ecg_streaming_DeviceStatus_MIN, 0, 0}
#define ecg_streaming_UsbConfig_init_default     {"", 0, {ecg_streaming_UsbTargetConfig_init_default, ecg_streaming_UsbTargetConfig_init_default}, 0}
#define ecg_streaming_EspMessage_init_zero       {0, {ecg_streaming_SensorFrame_init_zero}}
#define ecg_streaming_SensorFrame_init_zero      {"", _ecg_streaming_SensorType_MIN, 0, 0, 0, {{NULL}, NULL}}
#define ecg_streaming_UsbDeviceInfo_init_zero    {"", "", 0, 0, _ecg_streaming_DeviceStatus_MIN, 0, {ecg_streaming_UsbTargetInfo_init_zero, ecg_streaming_UsbTargetInfo_init_zero}}
#define ecg_streaming_UsbConfigAck_init_zero     {"", 0, "", ""}
#define ecg_streaming_BleNotificationDebug_init_zero {"", 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define ecg_streaming_CollectorToEspMessage_init_zero {0, {ecg_streaming_UsbConfig_init_zero}}
#define ecg_streaming_UsbTargetConfig_init_zero  {"", 0, 0}
#define ecg_streaming_UsbTargetInfo_init_zero    {"", 0, _ecg_streaming_DeviceStatus_MIN, 0, 0}
#define ecg_streaming_UsbConfig_init_zero        {"", 0, {ecg_streaming_UsbTargetConfig_init_zero, ecg_streaming_UsbTargetConfig_init_zero}, 0}

/* Field tags (for use in manual encoding/decoding) */
#define ecg_streaming_SensorFrame_device_id_tag  1
#define ecg_streaming_SensorFrame_sensor_type_tag 2
#define ecg_streaming_SensorFrame_polar_clock_us_tag 3
#define ecg_streaming_SensorFrame_receiver_clock_us_tag 4
#define ecg_streaming_SensorFrame_sample_rate_tag 5
#define ecg_streaming_SensorFrame_raw_data_tag   6
#define ecg_streaming_UsbConfigAck_esp_id_tag    1
#define ecg_streaming_UsbConfigAck_accepted_tag  2
#define ecg_streaming_UsbConfigAck_message_tag   3
#define ecg_streaming_UsbConfigAck_target_device_id_tag 4
#define ecg_streaming_BleNotificationDebug_device_id_tag 1
#define ecg_streaming_BleNotificationDebug_frame_type_tag 2
#define ecg_streaming_BleNotificationDebug_pmd_type_tag 3
#define ecg_streaming_BleNotificationDebug_notif_len_tag 4
#define ecg_streaming_BleNotificationDebug_sample_count_tag 5
#define ecg_streaming_BleNotificationDebug_polar_clock_us_tag 6
#define ecg_streaming_BleNotificationDebug_interval_us_tag 7
#define ecg_streaming_BleNotificationDebug_notification_index_tag 8
#define ecg_streaming_BleNotificationDebug_conn_interval_ms_tag 9
#define ecg_streaming_BleNotificationDebug_mtu_tag 10
#define ecg_streaming_UsbTargetConfig_target_device_id_tag 1
#define ecg_streaming_UsbTargetConfig_ecg_sample_rate_tag 2
#define ecg_streaming_UsbTargetConfig_acc_sample_rate_tag 3
#define ecg_streaming_UsbTargetInfo_target_device_id_tag 1
#define ecg_streaming_UsbTargetInfo_polar_connected_tag 2
#define ecg_streaming_UsbTargetInfo_polar_status_tag 3
#define ecg_streaming_UsbTargetInfo_ecg_sample_rate_tag 4
#define ecg_streaming_UsbTargetInfo_acc_sample_rate_tag 5
#define ecg_streaming_UsbDeviceInfo_esp_id_tag   1
#define ecg_streaming_UsbDeviceInfo_firmware_version_tag 2
#define ecg_streaming_UsbDeviceInfo_config_required_tag 3
#define ecg_streaming_UsbDeviceInfo_polar_connected_tag 4
#define ecg_streaming_UsbDeviceInfo_polar_status_tag 5
#define ecg_streaming_UsbDeviceInfo_targets_tag  6
#define ecg_streaming_EspMessage_sensor_frame_tag 1
#define ecg_streaming_EspMessage_device_info_tag 2
#define ecg_streaming_EspMessage_config_ack_tag  3
#define ecg_streaming_EspMessage_ble_debug_tag   4
#define ecg_streaming_UsbConfig_esp_id_tag       1
#define ecg_streaming_UsbConfig_targets_tag      2
#define ecg_streaming_UsbConfig_persist_tag      3
#define ecg_streaming_CollectorToEspMessage_config_tag 1

/* Struct field encoding specification for nanopb */
#define ecg_streaming_EspMessage_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,sensor_frame,message.sensor_frame),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,device_info,message.device_info),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,config_ack,message.config_ack),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,ble_debug,message.ble_debug),   4)
#define ecg_streaming_EspMessage_CALLBACK NULL
#define ecg_streaming_EspMessage_DEFAULT NULL
#define ecg_streaming_EspMessage_message_sensor_frame_MSGTYPE ecg_streaming_SensorFrame
#define ecg_streaming_EspMessage_message_device_info_MSGTYPE ecg_streaming_UsbDeviceInfo
#define ecg_streaming_EspMessage_message_config_ack_MSGTYPE ecg_streaming_UsbConfigAck
#define ecg_streaming_EspMessage_message_ble_debug_MSGTYPE ecg_streaming_BleNotificationDebug

#define ecg_streaming_SensorFrame_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   device_id,         1) \
X(a, STATIC,   SINGULAR, UENUM,    sensor_type,       2) \
X(a, STATIC,   SINGULAR, UINT64,   polar_clock_us,    3) \
X(a, STATIC,   SINGULAR, UINT64,   receiver_clock_us,   4) \
X(a, STATIC,   SINGULAR, INT32,    sample_rate,       5) \
X(a, CALLBACK, SINGULAR, BYTES,    raw_data,          6)
#define ecg_streaming_SensorFrame_CALLBACK pb_default_field_callback
#define ecg_streaming_SensorFrame_DEFAULT NULL

#define ecg_streaming_UsbDeviceInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   esp_id,            1) \
X(a, STATIC,   SINGULAR, STRING,   firmware_version,   2) \
X(a, STATIC,   SINGULAR, BOOL,     config_required,   3) \
X(a, STATIC,   SINGULAR, BOOL,     polar_connected,   4) \
X(a, STATIC,   SINGULAR, UENUM,    polar_status,      5) \
X(a, STATIC,   REPEATED, MESSAGE,  targets,           6)
#define ecg_streaming_UsbDeviceInfo_CALLBACK NULL
#define ecg_streaming_UsbDeviceInfo_DEFAULT NULL
#define ecg_streaming_UsbDeviceInfo_targets_MSGTYPE ecg_streaming_UsbTargetInfo

#define ecg_streaming_UsbConfigAck_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   esp_id,            1) \
X(a, STATIC,   SINGULAR, BOOL,     accepted,          2) \
X(a, STATIC,   SINGULAR, STRING,   message,           3) \
X(a, STATIC,   SINGULAR, STRING,   target_device_id,   4)
#define ecg_streaming_UsbConfigAck_CALLBACK NULL
#define ecg_streaming_UsbConfigAck_DEFAULT NULL

#define ecg_streaming_BleNotificationDebug_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   device_id,         1) \
X(a, STATIC,   SINGULAR, UINT32,   frame_type,        2) \
X(a, STATIC,   SINGULAR, UINT32,   pmd_type,          3) \
X(a, STATIC,   SINGULAR, UINT32,   notif_len,         4) \
X(a, STATIC,   SINGULAR, UINT32,   sample_count,      5) \
X(a, STATIC,   SINGULAR, UINT64,   polar_clock_us,    6) \
X(a, STATIC,   SINGULAR, UINT32,   interval_us,       7) \
X(a, STATIC,   SINGULAR, UINT64,   notification_index,   8) \
X(a, STATIC,   SINGULAR, UINT32,   conn_interval_ms,   9) \
X(a, STATIC,   SINGULAR, UINT32,   mtu,              10)
#define ecg_streaming_BleNotificationDebug_CALLBACK NULL
#define ecg_streaming_BleNotificationDebug_DEFAULT NULL

#define ecg_streaming_CollectorToEspMessage_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,config,message.config),   1)
#define ecg_streaming_CollectorToEspMessage_CALLBACK NULL
#define ecg_streaming_CollectorToEspMessage_DEFAULT NULL
#define ecg_streaming_CollectorToEspMessage_message_config_MSGTYPE ecg_streaming_UsbConfig

#define ecg_streaming_UsbTargetConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   target_device_id,   1) \
X(a, STATIC,   SINGULAR, INT32,    ecg_sample_rate,   2) \
X(a, STATIC,   SINGULAR, INT32,    acc_sample_rate,   3)
#define ecg_streaming_UsbTargetConfig_CALLBACK NULL
#define ecg_streaming_UsbTargetConfig_DEFAULT NULL

#define ecg_streaming_UsbTargetInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   target_device_id,   1) \
X(a, STATIC,   SINGULAR, BOOL,     polar_connected,   2) \
X(a, STATIC,   SINGULAR, UENUM,    polar_status,      3) \
X(a, STATIC,   SINGULAR, INT32,    ecg_sample_rate,   4) \
X(a, STATIC,   SINGULAR, INT32,    acc_sample_rate,   5)
#define ecg_streaming_UsbTargetInfo_CALLBACK NULL
#define ecg_streaming_UsbTargetInfo_DEFAULT NULL

#define ecg_streaming_UsbConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   esp_id,            1) \
X(a, STATIC,   REPEATED, MESSAGE,  targets,           2) \
X(a, STATIC,   SINGULAR, BOOL,     persist,           3)
#define ecg_streaming_UsbConfig_CALLBACK NULL
#define ecg_streaming_UsbConfig_DEFAULT NULL
#define ecg_streaming_UsbConfig_targets_MSGTYPE ecg_streaming_UsbTargetConfig

extern const pb_msgdesc_t ecg_streaming_EspMessage_msg;
extern const pb_msgdesc_t ecg_streaming_SensorFrame_msg;
extern const pb_msgdesc_t ecg_streaming_UsbDeviceInfo_msg;
extern const pb_msgdesc_t ecg_streaming_UsbConfigAck_msg;
extern const pb_msgdesc_t ecg_streaming_BleNotificationDebug_msg;
extern const pb_msgdesc_t ecg_streaming_CollectorToEspMessage_msg;
extern const pb_msgdesc_t ecg_streaming_UsbTargetConfig_msg;
extern const pb_msgdesc_t ecg_streaming_UsbTargetInfo_msg;
extern const pb_msgdesc_t ecg_streaming_UsbConfig_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ecg_streaming_EspMessage_fields &ecg_streaming_EspMessage_msg
#define ecg_streaming_SensorFrame_fields &ecg_streaming_SensorFrame_msg
#define ecg_streaming_UsbDeviceInfo_fields &ecg_streaming_UsbDeviceInfo_msg
#define ecg_streaming_UsbConfigAck_fields &ecg_streaming_UsbConfigAck_msg
#define ecg_streaming_BleNotificationDebug_fields &ecg_streaming_BleNotificationDebug_msg
#define ecg_streaming_CollectorToEspMessage_fields &ecg_streaming_CollectorToEspMessage_msg
#define ecg_streaming_UsbTargetConfig_fields &ecg_streaming_UsbTargetConfig_msg
#define ecg_streaming_UsbTargetInfo_fields &ecg_streaming_UsbTargetInfo_msg
#define ecg_streaming_UsbConfig_fields &ecg_streaming_UsbConfig_msg

/* Maximum encoded size of messages (where known) */
/* ecg_streaming_EspMessage_size depends on runtime parameters */
/* ecg_streaming_SensorFrame_size depends on runtime parameters */
#define ECG_STREAMING_ESP_COLLECTOR_PB_H_MAX_SIZE ecg_streaming_UsbDeviceInfo_size
#define ecg_streaming_BleNotificationDebug_size  130
#define ecg_streaming_CollectorToEspMessage_size 251
#define ecg_streaming_UsbConfigAck_size          265
#define ecg_streaming_UsbConfig_size             248
#define ecg_streaming_UsbDeviceInfo_size         294
#define ecg_streaming_UsbTargetConfig_size       88
#define ecg_streaming_UsbTargetInfo_size         92

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
