/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_ECG_STREAMING_ESP_COLLECTOR_PB_H_INCLUDED
#define PB_ECG_STREAMING_ESP_COLLECTOR_PB_H_INCLUDED
#include <pb.h>
#include "common.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Sensor type enumeration */
typedef enum _ecg_streaming_SensorType {
    ecg_streaming_SensorType_SENSOR_TYPE_ECG = 0,
    ecg_streaming_SensorType_SENSOR_TYPE_ACCELEROMETER = 1
} ecg_streaming_SensorType;

/* Struct definitions */
/* Unified sensor frame from Polar device (ECG or Accelerometer)
 ESP32 receives PMD frame from Polar H10, timestamps it with local time, and forwards */
typedef struct _ecg_streaming_SensorFrame {
    char device_id[65]; /* Polar device ID (e.g., "Polar H10 ABC123") */
    ecg_streaming_SensorType sensor_type; /* Type of sensor data (ECG or ACC) */
    uint64_t polar_clock_us; /* Polar device clock - microseconds since Polar device boot (last sample timestamp) */
    uint64_t receiver_clock_us; /* Receiver device clock - microseconds since receiver boot (ESP32 or collector) */
    /* NOTE: This is NOT always epoch time! */
    int32_t sample_rate; /* Sample rate in Hz */
    pb_callback_t raw_data; /* Raw PMD frame data (unparsed, for collector to process) */
} ecg_streaming_SensorFrame;

/* USB device identity and status information
 Sent by ESP32 on connection or when status changes */
typedef struct _ecg_streaming_UsbDeviceInfo {
    char esp_id[65]; /* Unique ESP32 identifier (e.g., MAC address) */
    char app_version[33]; /* Firmware app version (our code) */
    char idf_version[33]; /* ESP-IDF version */
    uint32_t protocol_version; /* USB protocol version */
    char current_target[65]; /* Currently configured Polar device ID (empty if none) */
    bool config_required; /* True if ESP needs configuration before starting */
    bool polar_connected; /* True if currently connected to Polar device */
    ecg_streaming_DeviceStatus polar_status; /* Status of Polar device connection */
    bool scanner_active; /* True if ESP is in BLE scanner mode */
    uint32_t scanner_request_id; /* Last scan request id processed by ESP */
} ecg_streaming_UsbDeviceInfo;

/* Configuration acknowledgment from ESP32
 Response to UsbConfig command */
typedef struct _ecg_streaming_UsbConfigAck {
    char esp_id[65]; /* ESP32 identifier */
    bool accepted; /* True if configuration was accepted */
    char message[129]; /* Human-readable status/error message */
    char target_device_id[65]; /* Configured target device ID (if accepted) */
} ecg_streaming_UsbConfigAck;

/* Debug telemetry for BLE PMD notifications
 Used for debugging ESP32-Polar communication issues */
typedef struct _ecg_streaming_BleNotificationDebug {
    char device_id[65]; /* Polar device ID */
    uint32_t frame_type; /* PMD frame type */
    uint32_t pmd_type; /* PMD measurement type */
    uint32_t notif_len; /* Notification length in bytes */
    uint32_t sample_count; /* Number of samples in notification */
    uint64_t polar_clock_us; /* Polar device clock (microseconds since Polar boot) */
    uint32_t interval_us; /* Time since last notification (microseconds) */
    uint64_t notification_index; /* Sequential notification counter */
    uint32_t conn_interval_ms; /* BLE connection interval (ms) */
    uint32_t mtu; /* Negotiated MTU */
} ecg_streaming_BleNotificationDebug;

typedef struct _ecg_streaming_EspMessage {
    pb_size_t which_message;
    union {
        ecg_streaming_SensorFrame sensor_frame;
        ecg_streaming_UsbDeviceInfo device_info;
        ecg_streaming_UsbConfigAck config_ack;
        ecg_streaming_BleNotificationDebug ble_debug;
    } message;
} ecg_streaming_EspMessage;

/* BLE sighting captured during a scanner-mode discovery pass */
typedef struct _ecg_streaming_BleScanSighting {
    char device_id[65]; /* Canonical device ID/name from advertisement */
    char name[65]; /* Advertisement local name */
    char address[21]; /* BLE MAC address */
    int32_t rssi; /* RSSI measured by scanning ESP */
    uint64_t seen_at_us; /* ESP wall clock when seen (microseconds since boot) */
} ecg_streaming_BleScanSighting;

/* BLE scanner-mode result from ESP32 to collector */
typedef struct _ecg_streaming_BleScanResult {
    uint32_t request_id; /* Echoes StartBleScan.request_id */
    char esp_id[65]; /* ESP32 identifier */
    pb_size_t sightings_count;
    ecg_streaming_BleScanSighting sightings[16];
    uint32_t duration_ms; /* Actual scan duration used by ESP */
} ecg_streaming_BleScanResult;

/* ESP discovery/scanner reports sent separately from operational traffic */
typedef struct _ecg_streaming_EspDiscoveryMessage {
    pb_size_t which_message;
    union {
        ecg_streaming_BleScanResult ble_scan_result;
    } message;
} ecg_streaming_EspDiscoveryMessage;

/* Configuration command for ESP32
 Tells ESP32 which Polar device to connect to and streaming parameters */
typedef struct _ecg_streaming_UsbConfig {
    char esp_id[65]; /* Target ESP32 identifier */
    char target_device_id[65]; /* Polar device ID to connect to */
    int32_t ecg_sample_rate; /* Requested ECG sample rate (Hz) */
    int32_t acc_sample_rate; /* Requested accelerometer sample rate (Hz) */
    bool persist; /* If true, save config to ESP32 flash */
} ecg_streaming_UsbConfig;

/* Command ESP to run one bounded BLE discovery pass and report sightings */
typedef struct _ecg_streaming_StartBleScan {
    char esp_id[65]; /* Target ESP32 identifier */
    uint32_t request_id; /* Collector-generated request id for idempotency */
    uint32_t duration_ms; /* Scan duration */
    char name_prefix[33]; /* Name filter (e.g., "Polar") */
} ecg_streaming_StartBleScan;

typedef struct _ecg_streaming_CollectorToEspMessage {
    pb_size_t which_message;
    union {
        ecg_streaming_UsbConfig config;
        ecg_streaming_StartBleScan start_ble_scan;
    } message;
} ecg_streaming_CollectorToEspMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _ecg_streaming_SensorType_MIN ecg_streaming_SensorType_SENSOR_TYPE_ECG
#define _ecg_streaming_SensorType_MAX ecg_streaming_SensorType_SENSOR_TYPE_ACCELEROMETER
#define _ecg_streaming_SensorType_ARRAYSIZE ((ecg_streaming_SensorType)(ecg_streaming_SensorType_SENSOR_TYPE_ACCELEROMETER+1))


#define ecg_streaming_SensorFrame_sensor_type_ENUMTYPE ecg_streaming_SensorType

#define ecg_streaming_UsbDeviceInfo_polar_status_ENUMTYPE ecg_streaming_DeviceStatus










/* Initializer values for message structs */
#define ecg_streaming_EspMessage_init_default    {0, {ecg_streaming_SensorFrame_init_default}}
#define ecg_streaming_SensorFrame_init_default   {"", _ecg_streaming_SensorType_MIN, 0, 0, 0, {{NULL}, NULL}}
#define ecg_streaming_UsbDeviceInfo_init_default {"", "", "", 0, "", 0, 0, _ecg_streaming_DeviceStatus_MIN, 0, 0}
#define ecg_streaming_UsbConfigAck_init_default  {"", 0, "", ""}
#define ecg_streaming_BleNotificationDebug_init_default {"", 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define ecg_streaming_BleScanSighting_init_default {"", "", "", 0, 0}
#define ecg_streaming_BleScanResult_init_default {0, "", 0, {ecg_streaming_BleScanSighting_init_default, ecg_streaming_BleScanSighting_init_default, ecg_streaming_BleScanSighting_init_default, ecg_streaming_BleScanSighting_init_default, ecg_streaming_BleScanSighting_init_default, ecg_streaming_BleScanSighting_init_default, ecg_streaming_BleScanSighting_init_default, ecg_streaming_BleScanSighting_init_default, ecg_streaming_BleScanSighting_init_default, ecg_streaming_BleScanSighting_init_default, ecg_streaming_BleScanSighting_init_default, ecg_streaming_BleScanSighting_init_default, ecg_streaming_BleScanSighting_init_default, ecg_streaming_BleScanSighting_init_default, ecg_streaming_BleScanSighting_init_default, ecg_streaming_BleScanSighting_init_default}, 0}
#define ecg_streaming_EspDiscoveryMessage_init_default {0, {ecg_streaming_BleScanResult_init_default}}
#define ecg_streaming_CollectorToEspMessage_init_default {0, {ecg_streaming_UsbConfig_init_default}}
#define ecg_streaming_UsbConfig_init_default     {"", "", 0, 0, 0}
#define ecg_streaming_StartBleScan_init_default  {"", 0, 0, ""}
#define ecg_streaming_EspMessage_init_zero       {0, {ecg_streaming_SensorFrame_init_zero}}
#define ecg_streaming_SensorFrame_init_zero      {"", _ecg_streaming_SensorType_MIN, 0, 0, 0, {{NULL}, NULL}}
#define ecg_streaming_UsbDeviceInfo_init_zero    {"", "", "", 0, "", 0, 0, _ecg_streaming_DeviceStatus_MIN, 0, 0}
#define ecg_streaming_UsbConfigAck_init_zero     {"", 0, "", ""}
#define ecg_streaming_BleNotificationDebug_init_zero {"", 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define ecg_streaming_BleScanSighting_init_zero  {"", "", "", 0, 0}
#define ecg_streaming_BleScanResult_init_zero    {0, "", 0, {ecg_streaming_BleScanSighting_init_zero, ecg_streaming_BleScanSighting_init_zero, ecg_streaming_BleScanSighting_init_zero, ecg_streaming_BleScanSighting_init_zero, ecg_streaming_BleScanSighting_init_zero, ecg_streaming_BleScanSighting_init_zero, ecg_streaming_BleScanSighting_init_zero, ecg_streaming_BleScanSighting_init_zero, ecg_streaming_BleScanSighting_init_zero, ecg_streaming_BleScanSighting_init_zero, ecg_streaming_BleScanSighting_init_zero, ecg_streaming_BleScanSighting_init_zero, ecg_streaming_BleScanSighting_init_zero, ecg_streaming_BleScanSighting_init_zero, ecg_streaming_BleScanSighting_init_zero, ecg_streaming_BleScanSighting_init_zero}, 0}
#define ecg_streaming_EspDiscoveryMessage_init_zero {0, {ecg_streaming_BleScanResult_init_zero}}
#define ecg_streaming_CollectorToEspMessage_init_zero {0, {ecg_streaming_UsbConfig_init_zero}}
#define ecg_streaming_UsbConfig_init_zero        {"", "", 0, 0, 0}
#define ecg_streaming_StartBleScan_init_zero     {"", 0, 0, ""}

/* Field tags (for use in manual encoding/decoding) */
#define ecg_streaming_SensorFrame_device_id_tag  1
#define ecg_streaming_SensorFrame_sensor_type_tag 2
#define ecg_streaming_SensorFrame_polar_clock_us_tag 3
#define ecg_streaming_SensorFrame_receiver_clock_us_tag 4
#define ecg_streaming_SensorFrame_sample_rate_tag 5
#define ecg_streaming_SensorFrame_raw_data_tag   6
#define ecg_streaming_UsbDeviceInfo_esp_id_tag   1
#define ecg_streaming_UsbDeviceInfo_app_version_tag 2
#define ecg_streaming_UsbDeviceInfo_idf_version_tag 3
#define ecg_streaming_UsbDeviceInfo_protocol_version_tag 4
#define ecg_streaming_UsbDeviceInfo_current_target_tag 5
#define ecg_streaming_UsbDeviceInfo_config_required_tag 6
#define ecg_streaming_UsbDeviceInfo_polar_connected_tag 7
#define ecg_streaming_UsbDeviceInfo_polar_status_tag 8
#define ecg_streaming_UsbDeviceInfo_scanner_active_tag 9
#define ecg_streaming_UsbDeviceInfo_scanner_request_id_tag 10
#define ecg_streaming_UsbConfigAck_esp_id_tag    1
#define ecg_streaming_UsbConfigAck_accepted_tag  2
#define ecg_streaming_UsbConfigAck_message_tag   3
#define ecg_streaming_UsbConfigAck_target_device_id_tag 4
#define ecg_streaming_BleNotificationDebug_device_id_tag 1
#define ecg_streaming_BleNotificationDebug_frame_type_tag 2
#define ecg_streaming_BleNotificationDebug_pmd_type_tag 3
#define ecg_streaming_BleNotificationDebug_notif_len_tag 4
#define ecg_streaming_BleNotificationDebug_sample_count_tag 5
#define ecg_streaming_BleNotificationDebug_polar_clock_us_tag 6
#define ecg_streaming_BleNotificationDebug_interval_us_tag 7
#define ecg_streaming_BleNotificationDebug_notification_index_tag 8
#define ecg_streaming_BleNotificationDebug_conn_interval_ms_tag 9
#define ecg_streaming_BleNotificationDebug_mtu_tag 10
#define ecg_streaming_EspMessage_sensor_frame_tag 1
#define ecg_streaming_EspMessage_device_info_tag 2
#define ecg_streaming_EspMessage_config_ack_tag  3
#define ecg_streaming_EspMessage_ble_debug_tag   4
#define ecg_streaming_BleScanSighting_device_id_tag 1
#define ecg_streaming_BleScanSighting_name_tag   2
#define ecg_streaming_BleScanSighting_address_tag 3
#define ecg_streaming_BleScanSighting_rssi_tag   4
#define ecg_streaming_BleScanSighting_seen_at_us_tag 5
#define ecg_streaming_BleScanResult_request_id_tag 1
#define ecg_streaming_BleScanResult_esp_id_tag   2
#define ecg_streaming_BleScanResult_sightings_tag 3
#define ecg_streaming_BleScanResult_duration_ms_tag 4
#define ecg_streaming_EspDiscoveryMessage_ble_scan_result_tag 1
#define ecg_streaming_UsbConfig_esp_id_tag       1
#define ecg_streaming_UsbConfig_target_device_id_tag 2
#define ecg_streaming_UsbConfig_ecg_sample_rate_tag 3
#define ecg_streaming_UsbConfig_acc_sample_rate_tag 4
#define ecg_streaming_UsbConfig_persist_tag      5
#define ecg_streaming_StartBleScan_esp_id_tag    1
#define ecg_streaming_StartBleScan_request_id_tag 2
#define ecg_streaming_StartBleScan_duration_ms_tag 3
#define ecg_streaming_StartBleScan_name_prefix_tag 4
#define ecg_streaming_CollectorToEspMessage_config_tag 1
#define ecg_streaming_CollectorToEspMessage_start_ble_scan_tag 2

/* Struct field encoding specification for nanopb */
#define ecg_streaming_EspMessage_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,sensor_frame,message.sensor_frame),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,device_info,message.device_info),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,config_ack,message.config_ack),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,ble_debug,message.ble_debug),   4)
#define ecg_streaming_EspMessage_CALLBACK NULL
#define ecg_streaming_EspMessage_DEFAULT NULL
#define ecg_streaming_EspMessage_message_sensor_frame_MSGTYPE ecg_streaming_SensorFrame
#define ecg_streaming_EspMessage_message_device_info_MSGTYPE ecg_streaming_UsbDeviceInfo
#define ecg_streaming_EspMessage_message_config_ack_MSGTYPE ecg_streaming_UsbConfigAck
#define ecg_streaming_EspMessage_message_ble_debug_MSGTYPE ecg_streaming_BleNotificationDebug

#define ecg_streaming_SensorFrame_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   device_id,         1) \
X(a, STATIC,   SINGULAR, UENUM,    sensor_type,       2) \
X(a, STATIC,   SINGULAR, UINT64,   polar_clock_us,    3) \
X(a, STATIC,   SINGULAR, UINT64,   receiver_clock_us,   4) \
X(a, STATIC,   SINGULAR, INT32,    sample_rate,       5) \
X(a, CALLBACK, SINGULAR, BYTES,    raw_data,          6)
#define ecg_streaming_SensorFrame_CALLBACK pb_default_field_callback
#define ecg_streaming_SensorFrame_DEFAULT NULL

#define ecg_streaming_UsbDeviceInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   esp_id,            1) \
X(a, STATIC,   SINGULAR, STRING,   app_version,       2) \
X(a, STATIC,   SINGULAR, STRING,   idf_version,       3) \
X(a, STATIC,   SINGULAR, UINT32,   protocol_version,   4) \
X(a, STATIC,   SINGULAR, STRING,   current_target,    5) \
X(a, STATIC,   SINGULAR, BOOL,     config_required,   6) \
X(a, STATIC,   SINGULAR, BOOL,     polar_connected,   7) \
X(a, STATIC,   SINGULAR, UENUM,    polar_status,      8) \
X(a, STATIC,   SINGULAR, BOOL,     scanner_active,    9) \
X(a, STATIC,   SINGULAR, UINT32,   scanner_request_id,  10)
#define ecg_streaming_UsbDeviceInfo_CALLBACK NULL
#define ecg_streaming_UsbDeviceInfo_DEFAULT NULL

#define ecg_streaming_UsbConfigAck_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   esp_id,            1) \
X(a, STATIC,   SINGULAR, BOOL,     accepted,          2) \
X(a, STATIC,   SINGULAR, STRING,   message,           3) \
X(a, STATIC,   SINGULAR, STRING,   target_device_id,   4)
#define ecg_streaming_UsbConfigAck_CALLBACK NULL
#define ecg_streaming_UsbConfigAck_DEFAULT NULL

#define ecg_streaming_BleNotificationDebug_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   device_id,         1) \
X(a, STATIC,   SINGULAR, UINT32,   frame_type,        2) \
X(a, STATIC,   SINGULAR, UINT32,   pmd_type,          3) \
X(a, STATIC,   SINGULAR, UINT32,   notif_len,         4) \
X(a, STATIC,   SINGULAR, UINT32,   sample_count,      5) \
X(a, STATIC,   SINGULAR, UINT64,   polar_clock_us,    6) \
X(a, STATIC,   SINGULAR, UINT32,   interval_us,       7) \
X(a, STATIC,   SINGULAR, UINT64,   notification_index,   8) \
X(a, STATIC,   SINGULAR, UINT32,   conn_interval_ms,   9) \
X(a, STATIC,   SINGULAR, UINT32,   mtu,              10)
#define ecg_streaming_BleNotificationDebug_CALLBACK NULL
#define ecg_streaming_BleNotificationDebug_DEFAULT NULL

#define ecg_streaming_BleScanSighting_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   device_id,         1) \
X(a, STATIC,   SINGULAR, STRING,   name,              2) \
X(a, STATIC,   SINGULAR, STRING,   address,           3) \
X(a, STATIC,   SINGULAR, INT32,    rssi,              4) \
X(a, STATIC,   SINGULAR, UINT64,   seen_at_us,        5)
#define ecg_streaming_BleScanSighting_CALLBACK NULL
#define ecg_streaming_BleScanSighting_DEFAULT NULL

#define ecg_streaming_BleScanResult_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   request_id,        1) \
X(a, STATIC,   SINGULAR, STRING,   esp_id,            2) \
X(a, STATIC,   REPEATED, MESSAGE,  sightings,         3) \
X(a, STATIC,   SINGULAR, UINT32,   duration_ms,       4)
#define ecg_streaming_BleScanResult_CALLBACK NULL
#define ecg_streaming_BleScanResult_DEFAULT NULL
#define ecg_streaming_BleScanResult_sightings_MSGTYPE ecg_streaming_BleScanSighting

#define ecg_streaming_EspDiscoveryMessage_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,ble_scan_result,message.ble_scan_result),   1)
#define ecg_streaming_EspDiscoveryMessage_CALLBACK NULL
#define ecg_streaming_EspDiscoveryMessage_DEFAULT NULL
#define ecg_streaming_EspDiscoveryMessage_message_ble_scan_result_MSGTYPE ecg_streaming_BleScanResult

#define ecg_streaming_CollectorToEspMessage_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,config,message.config),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,start_ble_scan,message.start_ble_scan),   2)
#define ecg_streaming_CollectorToEspMessage_CALLBACK NULL
#define ecg_streaming_CollectorToEspMessage_DEFAULT NULL
#define ecg_streaming_CollectorToEspMessage_message_config_MSGTYPE ecg_streaming_UsbConfig
#define ecg_streaming_CollectorToEspMessage_message_start_ble_scan_MSGTYPE ecg_streaming_StartBleScan

#define ecg_streaming_UsbConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   esp_id,            1) \
X(a, STATIC,   SINGULAR, STRING,   target_device_id,   2) \
X(a, STATIC,   SINGULAR, INT32,    ecg_sample_rate,   3) \
X(a, STATIC,   SINGULAR, INT32,    acc_sample_rate,   4) \
X(a, STATIC,   SINGULAR, BOOL,     persist,           5)
#define ecg_streaming_UsbConfig_CALLBACK NULL
#define ecg_streaming_UsbConfig_DEFAULT NULL

#define ecg_streaming_StartBleScan_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   esp_id,            1) \
X(a, STATIC,   SINGULAR, UINT32,   request_id,        2) \
X(a, STATIC,   SINGULAR, UINT32,   duration_ms,       3) \
X(a, STATIC,   SINGULAR, STRING,   name_prefix,       4)
#define ecg_streaming_StartBleScan_CALLBACK NULL
#define ecg_streaming_StartBleScan_DEFAULT NULL

extern const pb_msgdesc_t ecg_streaming_EspMessage_msg;
extern const pb_msgdesc_t ecg_streaming_SensorFrame_msg;
extern const pb_msgdesc_t ecg_streaming_UsbDeviceInfo_msg;
extern const pb_msgdesc_t ecg_streaming_UsbConfigAck_msg;
extern const pb_msgdesc_t ecg_streaming_BleNotificationDebug_msg;
extern const pb_msgdesc_t ecg_streaming_BleScanSighting_msg;
extern const pb_msgdesc_t ecg_streaming_BleScanResult_msg;
extern const pb_msgdesc_t ecg_streaming_EspDiscoveryMessage_msg;
extern const pb_msgdesc_t ecg_streaming_CollectorToEspMessage_msg;
extern const pb_msgdesc_t ecg_streaming_UsbConfig_msg;
extern const pb_msgdesc_t ecg_streaming_StartBleScan_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ecg_streaming_EspMessage_fields &ecg_streaming_EspMessage_msg
#define ecg_streaming_SensorFrame_fields &ecg_streaming_SensorFrame_msg
#define ecg_streaming_UsbDeviceInfo_fields &ecg_streaming_UsbDeviceInfo_msg
#define ecg_streaming_UsbConfigAck_fields &ecg_streaming_UsbConfigAck_msg
#define ecg_streaming_BleNotificationDebug_fields &ecg_streaming_BleNotificationDebug_msg
#define ecg_streaming_BleScanSighting_fields &ecg_streaming_BleScanSighting_msg
#define ecg_streaming_BleScanResult_fields &ecg_streaming_BleScanResult_msg
#define ecg_streaming_EspDiscoveryMessage_fields &ecg_streaming_EspDiscoveryMessage_msg
#define ecg_streaming_CollectorToEspMessage_fields &ecg_streaming_CollectorToEspMessage_msg
#define ecg_streaming_UsbConfig_fields &ecg_streaming_UsbConfig_msg
#define ecg_streaming_StartBleScan_fields &ecg_streaming_StartBleScan_msg

/* Maximum encoded size of messages (where known) */
/* ecg_streaming_EspMessage_size depends on runtime parameters */
/* ecg_streaming_SensorFrame_size depends on runtime parameters */
#define ECG_STREAMING_ESP_COLLECTOR_PB_H_MAX_SIZE ecg_streaming_EspDiscoveryMessage_size
#define ecg_streaming_BleNotificationDebug_size  130
#define ecg_streaming_BleScanResult_size         2942
#define ecg_streaming_BleScanSighting_size       176
#define ecg_streaming_CollectorToEspMessage_size 159
#define ecg_streaming_EspDiscoveryMessage_size   2945
#define ecg_streaming_StartBleScan_size          112
#define ecg_streaming_UsbConfigAck_size          265
#define ecg_streaming_UsbConfig_size             156
#define ecg_streaming_UsbDeviceInfo_size         220

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
