/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_ECG_STREAMING_USB_TRANSPORT_PB_H_INCLUDED
#define PB_ECG_STREAMING_USB_TRANSPORT_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _ecg_streaming_UsbPayloadType {
    ecg_streaming_UsbPayloadType_USB_PAYLOAD_TYPE_UNKNOWN = 0,
    ecg_streaming_UsbPayloadType_USB_PAYLOAD_TYPE_ESP_MESSAGE = 1, /* ESP32 -> Collector operational traffic */
    ecg_streaming_UsbPayloadType_USB_PAYLOAD_TYPE_COLLECTOR_TO_ESP = 2, /* Collector -> ESP32 */
    ecg_streaming_UsbPayloadType_USB_PAYLOAD_TYPE_ESP_DISCOVERY_MESSAGE = 3 /* ESP32 -> Collector discovery/scanner traffic */
} ecg_streaming_UsbPayloadType;

/* Struct definitions */
typedef struct _ecg_streaming_UsbFrame {
    uint32_t version; /* Protocol version */
    ecg_streaming_UsbPayloadType payload_type; /* Type of message in payload */
    uint32_t seq; /* Sequence number for ordering/deduplication */
    uint32_t crc32; /* CRC32 checksum of payload */
    pb_callback_t payload; /* Serialized ESP/collector transport payload */
} ecg_streaming_UsbFrame;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _ecg_streaming_UsbPayloadType_MIN ecg_streaming_UsbPayloadType_USB_PAYLOAD_TYPE_UNKNOWN
#define _ecg_streaming_UsbPayloadType_MAX ecg_streaming_UsbPayloadType_USB_PAYLOAD_TYPE_ESP_DISCOVERY_MESSAGE
#define _ecg_streaming_UsbPayloadType_ARRAYSIZE ((ecg_streaming_UsbPayloadType)(ecg_streaming_UsbPayloadType_USB_PAYLOAD_TYPE_ESP_DISCOVERY_MESSAGE+1))

#define ecg_streaming_UsbFrame_payload_type_ENUMTYPE ecg_streaming_UsbPayloadType


/* Initializer values for message structs */
#define ecg_streaming_UsbFrame_init_default      {0, _ecg_streaming_UsbPayloadType_MIN, 0, 0, {{NULL}, NULL}}
#define ecg_streaming_UsbFrame_init_zero         {0, _ecg_streaming_UsbPayloadType_MIN, 0, 0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define ecg_streaming_UsbFrame_version_tag       1
#define ecg_streaming_UsbFrame_payload_type_tag  2
#define ecg_streaming_UsbFrame_seq_tag           3
#define ecg_streaming_UsbFrame_crc32_tag         4
#define ecg_streaming_UsbFrame_payload_tag       5

/* Struct field encoding specification for nanopb */
#define ecg_streaming_UsbFrame_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   version,           1) \
X(a, STATIC,   SINGULAR, UENUM,    payload_type,      2) \
X(a, STATIC,   SINGULAR, FIXED32,  seq,               3) \
X(a, STATIC,   SINGULAR, FIXED32,  crc32,             4) \
X(a, CALLBACK, SINGULAR, BYTES,    payload,           5)
#define ecg_streaming_UsbFrame_CALLBACK pb_default_field_callback
#define ecg_streaming_UsbFrame_DEFAULT NULL

extern const pb_msgdesc_t ecg_streaming_UsbFrame_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ecg_streaming_UsbFrame_fields &ecg_streaming_UsbFrame_msg

/* Maximum encoded size of messages (where known) */
/* ecg_streaming_UsbFrame_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
