/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "usb_transport.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ecg_streaming_UsbFrame, ecg_streaming_UsbFrame, AUTO)





